[package]
name = "vm32bits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
mem_storage = "0.1.1"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
